%YAML:1.0

#common parameters
savePath: "/home/zhu/LaserCameraCal_ws/data/log/"
bag_path: "/home/zhu/LaserCameraCal_ws/data/50_scan_camera_ros1.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/color/image_raw"

# tag info
# tag_type: 2 # 1: kalibr_tag, 2: apriltag
# tag_size: 0.165 # tag size, unit meter
# tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
# black_border: 1 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size: 0.055 # tag size, unit meter
tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720

distortion_parameters:
   k1: 0.006776703521609306
   k2: -0.04969489201903343
   p1: 0.00015696707123424858
   p2: 0.00028245517751201987

projection_parameters:
   fx: 692.6710205078125
   fy: 693.0302734375
   cx: 644.2572631835938
   cy: 362.542236328125

# distortion_parameters:
#    k1: 0.0
#    k2: 0.0
#    p1: 0.0
#    p2: 0.0

# projection_parameters:
#    fx: 367.049931000148
#    fy: 366.94446918887405
#    cx: 368.7202381120387
#    cy: 241.13814795878562

